name: Deploy to AWS S3

permissions:
  id-token: write
  contents: read
  packages: read

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-central-1"
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: out
          bucket: "niklaskors"
          dist-id: "E1YYN7LF9OYTQ1"
          invalidation: / *
